sudo: required
language: python
dist: xenial

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

services:
 - postgresql
matrix:
  include:
    - python: "2.7"
      env: GS_VERSION=2.12.x
    - python: "2.7"
      env: GS_VERSION=2.13.x
    - python: "2.7"
      env: GS_VERSION=2.14.x
    - python: "2.7"
      env: GS_VERSION=2.15.x
    - python: "2.7"
      env: GS_VERSION=master
    - python: "3.6"
      env: GS_VERSION=2.12.x
    - python: "3.6"
      env: GS_VERSION=2.13.x
    - python: "3.6"
      env: GS_VERSION=2.14.x
    - python: "3.6"
      env: GS_VERSION=2.15.x
    - python: "3.6"
      env: GS_VERSION=master
    - python: "3.7"
      env: GS_VERSION=2.12.x
    - python: "3.7"
      env: GS_VERSION=2.13.x
    - python: "3.7"
      env: GS_VERSION=2.14.x
    - python: "3.7"
      env: GS_VERSION=2.15.x
    - python: "3.7"
      env: GS_VERSION=master
install:
  - sudo apt-get -qq -y update
  - sudo apt-get install -y --force-yes openjdk-8-jdk --no-install-recommends
  - java -version
  - which java
  - update-alternatives --list java
  - mkdir gs
  - pushd gs
  - wget http://central.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.12.v20180830/jetty-runner-9.4.12.v20180830.jar
  - wget https://build.geoserver.org/geoserver/${GS_VERSION}/geoserver-${GS_VERSION}-latest-war.zip
  - unzip geoserver-${GS_VERSION}-latest-war.zip
  - popd
  - pip install .
  - pip install psycopg2
before_script:
  - if [[ "$GS_VERSION" == "2.16.x" ]] || [[ "$GS_VERSION" == "2.15.x" ]] || [[ "$GS_VERSION" == "master" ]]; then
    /usr/local/lib/jvm/openjdk11/bin/java -Xmx1024m -Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true -jar gs/jetty-runner-9.4.12.v20180830.jar --path /geoserver gs/geoserver.war > /dev/null 2>&1 &
    else
    /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xmx1024m -Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true -jar gs/jetty-runner-9.4.12.v20180830.jar --path /geoserver gs/geoserver.war > /dev/null 2>&1 &
    fi
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create database db;"
  - psql -U postgres -d db -c "create extension postgis"
  - psql -U postgres -c "alter user postgres with password 'password';"
  - sleep 30
script:
  - python setup.py test
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master
